"""
ApexCare Clinical Practice Guidelines & Evidence-Based Order Sets
Comprehensive standard operating procedures, admission criteria, and clinical pathways.
"""
from typing import Dict, List, Any, Optional
from dataclasses import dataclass

@dataclass
class ClinicalPathway:
    pathway_code: str
    condition_name: str
    icd10_primary: str
    triage_acuity_target: str
    stat_investigations: List[str]
    first_line_pharmacology: List[str]
    monitoring_parameters: List[str]
    discharge_readiness_criteria: List[str]
    clinical_evidence_source: str

CLINICAL_PATHWAYS_DATABASE: Dict[str, ClinicalPathway] = {
    "CP-ACS-01-01": ClinicalPathway(
        pathway_code="CP-ACS-01-01",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 1",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-02": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-02",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 2",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-03": ClinicalPathway(
        pathway_code="CP-STROKE-03-03",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 3",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-04": ClinicalPathway(
        pathway_code="CP-DKA-04-04",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 4",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-05": ClinicalPathway(
        pathway_code="CP-COPD-05-05",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 5",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-06": ClinicalPathway(
        pathway_code="CP-ACS-01-06",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 6",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-07": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-07",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 7",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-08": ClinicalPathway(
        pathway_code="CP-STROKE-03-08",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 8",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-09": ClinicalPathway(
        pathway_code="CP-DKA-04-09",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 9",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-10": ClinicalPathway(
        pathway_code="CP-COPD-05-10",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 10",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-11": ClinicalPathway(
        pathway_code="CP-ACS-01-11",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 11",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-12": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-12",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 12",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-13": ClinicalPathway(
        pathway_code="CP-STROKE-03-13",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 13",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-14": ClinicalPathway(
        pathway_code="CP-DKA-04-14",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 14",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-15": ClinicalPathway(
        pathway_code="CP-COPD-05-15",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 15",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-16": ClinicalPathway(
        pathway_code="CP-ACS-01-16",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 16",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-17": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-17",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 17",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-18": ClinicalPathway(
        pathway_code="CP-STROKE-03-18",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 18",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-19": ClinicalPathway(
        pathway_code="CP-DKA-04-19",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 19",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-20": ClinicalPathway(
        pathway_code="CP-COPD-05-20",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 20",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-21": ClinicalPathway(
        pathway_code="CP-ACS-01-21",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 21",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-22": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-22",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 22",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-23": ClinicalPathway(
        pathway_code="CP-STROKE-03-23",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 23",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-24": ClinicalPathway(
        pathway_code="CP-DKA-04-24",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 24",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-25": ClinicalPathway(
        pathway_code="CP-COPD-05-25",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 25",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-26": ClinicalPathway(
        pathway_code="CP-ACS-01-26",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 26",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-27": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-27",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 27",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-28": ClinicalPathway(
        pathway_code="CP-STROKE-03-28",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 28",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-29": ClinicalPathway(
        pathway_code="CP-DKA-04-29",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 29",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-30": ClinicalPathway(
        pathway_code="CP-COPD-05-30",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 30",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-31": ClinicalPathway(
        pathway_code="CP-ACS-01-31",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 31",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-32": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-32",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 32",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-33": ClinicalPathway(
        pathway_code="CP-STROKE-03-33",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 33",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-34": ClinicalPathway(
        pathway_code="CP-DKA-04-34",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 34",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-35": ClinicalPathway(
        pathway_code="CP-COPD-05-35",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 35",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-36": ClinicalPathway(
        pathway_code="CP-ACS-01-36",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 36",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-37": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-37",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 37",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-38": ClinicalPathway(
        pathway_code="CP-STROKE-03-38",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 38",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-39": ClinicalPathway(
        pathway_code="CP-DKA-04-39",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 39",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-40": ClinicalPathway(
        pathway_code="CP-COPD-05-40",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 40",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-41": ClinicalPathway(
        pathway_code="CP-ACS-01-41",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 41",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-42": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-42",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 42",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-43": ClinicalPathway(
        pathway_code="CP-STROKE-03-43",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 43",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-44": ClinicalPathway(
        pathway_code="CP-DKA-04-44",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 44",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-45": ClinicalPathway(
        pathway_code="CP-COPD-05-45",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 45",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-46": ClinicalPathway(
        pathway_code="CP-ACS-01-46",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 46",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-47": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-47",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 47",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-48": ClinicalPathway(
        pathway_code="CP-STROKE-03-48",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 48",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-49": ClinicalPathway(
        pathway_code="CP-DKA-04-49",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 49",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-50": ClinicalPathway(
        pathway_code="CP-COPD-05-50",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 50",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-51": ClinicalPathway(
        pathway_code="CP-ACS-01-51",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 51",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-52": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-52",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 52",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-53": ClinicalPathway(
        pathway_code="CP-STROKE-03-53",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 53",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-54": ClinicalPathway(
        pathway_code="CP-DKA-04-54",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 54",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
    "CP-COPD-05-55": ClinicalPathway(
        pathway_code="CP-COPD-05-55",
        condition_name="Acute Exacerbation of COPD — Clinical Sub-Pathway Tier 55",
        icd10_primary="J44.1",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Arterial Blood Gas (ABG)', 'Chest X-Ray PA/Lateral', 'ECG to rule out cor pulmonale / arrhythmias', 'CBC with differential for eosinophils', 'Sputum Gram stain and culture'],
        first_line_pharmacology=['Duoneb (Albuterol 2.5mg + Ipratropium 0.5mg) nebulization q20m x 3', 'Methylprednisolone 60mg IV or Prednisone 40mg PO daily', 'Azithromycin 500mg IV/PO daily or Ceftriaxone 1g IV daily', 'Non-invasive Positive Pressure Ventilation (BiPAP) for pH < 7.35'],
        monitoring_parameters=['Continuous pulse oximetry target SpO2 88-92%', 'Serial ABG at 2 hours post-BiPAP initiation', 'Respiratory rate and accessory muscle usage score'],
        discharge_readiness_criteria=['pH >= 7.35 maintained on room air or baseline nasal cannula', 'Inhaler technique verified with Respiratory Therapy', 'Steroid taper schedule and Action Plan provided to patient'],
        clinical_evidence_source="Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024",
    ),
    "CP-ACS-01-56": ClinicalPathway(
        pathway_code="CP-ACS-01-56",
        condition_name="Acute Coronary Syndrome / STEMI — Clinical Sub-Pathway Tier 56",
        icd10_primary="I21.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT 12-lead ECG within 10 minutes', 'High-sensitivity Troponin I at 0h and 3h', 'Electrolytes (K+, Mg2+)', 'Coagulation profile (PT/INR, aPTT)', 'Bedside Echocardiogram'],
        first_line_pharmacology=['Aspirin 325mg PO chewed immediately', 'Ticagrelor 180mg PO or Clopidogrel 600mg PO loading', 'Unfractionated Heparin 60 units/kg IV bolus', 'Atorvastatin 80mg PO', 'Sublingual Nitroglycerin 0.4mg q5m PRN'],
        monitoring_parameters=['Continuous 12-lead ST-segment telemetry', 'Invasive arterial blood pressure monitoring', 'Urine output hourly', 'Serial Cardiac Enzymes'],
        discharge_readiness_criteria=['Door-to-balloon PCI time < 90 mins achieved', 'Hemodynamic stability without inotropic support', 'Resolution of ischemic chest discomfort', 'Ejection fraction documented > 40%'],
        clinical_evidence_source="AHA/ACC 2024 STEMI Clinical Guidelines",
    ),
    "CP-SEPSIS-02-57": ClinicalPathway(
        pathway_code="CP-SEPSIS-02-57",
        condition_name="Severe Sepsis & Septic Shock — Clinical Sub-Pathway Tier 57",
        icd10_primary="A41.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Serum L-Lactate within 1 hour', 'Two sets of blood cultures (aerobic + anaerobic) prior to antibiotics', 'Complete Blood Count with differential', 'Comprehensive Metabolic Panel', 'Procalcitonin', 'ABG with PaO2/FiO2 ratio'],
        first_line_pharmacology=['Crystalloid IV fluids 30 mL/kg within first 3 hours', 'Broad-spectrum IV antimicrobials within 1 hour (Vancomycin + Cefepime)', 'Norepinephrine infusion titrated to MAP >= 65 mmHg', 'Hydrocortisone 200mg/day IV for refractory shock'],
        monitoring_parameters=['Continuous arterial line blood pressure monitoring', 'Central Venous Pressure (CVP 8-12 mmHg)', 'ScvO2 saturation >= 70%', 'Serial lactate clearance every 2 hours until normal'],
        discharge_readiness_criteria=['Normalized serum lactate (< 2.0 mmol/L)', 'Off all vasopressor support for >= 24 hours', 'Afebrile for >= 48 hours on targeted oral antimicrobials', 'Adequate enteral oral nutrition tolerated'],
        clinical_evidence_source="Surviving Sepsis Campaign International Guidelines 2024",
    ),
    "CP-STROKE-03-58": ClinicalPathway(
        pathway_code="CP-STROKE-03-58",
        condition_name="Acute Ischemic Stroke (Thrombolysis Pathway) — Clinical Sub-Pathway Tier 58",
        icd10_primary="I63.9",
        triage_acuity_target="ESI-1_IMMEDIATE",
        stat_investigations=['STAT Non-contrast Head CT within 20 mins of arrival', 'CT Angiography head and neck vessels', 'Point-of-care blood glucose', 'Fingerstick INR', 'CBC and Platelets'],
        first_line_pharmacology=['IV Tenecteplase 0.25 mg/kg (max 25mg) bolus within 4.5h window', 'Labetalol 10-20mg IV if BP > 185/110 prior to thrombolysis', 'Nicardipine IV continuous infusion for tight BP control < 180/105'],
        monitoring_parameters=['NIHSS Stroke Scale hourly for first 24 hours', 'Continuous neurological pupil checks', 'Continuous automated NIBP every 15 mins during infusion'],
        discharge_readiness_criteria=['24-hour post-thrombolysis non-contrast head CT clears intracranial hemorrhage', 'Dysphagia swallow screen completed by Speech Pathology', 'Secondary prevention statin and antiplatelet initiated at 24h', 'Physical and Occupational therapy functional mobility clearance'],
        clinical_evidence_source="AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke",
    ),
    "CP-DKA-04-59": ClinicalPathway(
        pathway_code="CP-DKA-04-59",
        condition_name="Diabetic Ketoacidosis (DKA) — Clinical Sub-Pathway Tier 59",
        icd10_primary="E11.65",
        triage_acuity_target="ESI-2_EMERGENT",
        stat_investigations=['STAT Point-of-care capillary blood glucose', 'Venous Blood Gas (pH and bicarbonate)', 'Serum Beta-hydroxybutyrate level', 'Basic Metabolic Panel for Anion Gap calculation', 'Urinalysis for ketones'],
        first_line_pharmacology=['IV Normal Saline (0.9% NaCl) 1000 mL/hr in hour 1', 'Regular Insulin IV continuous infusion 0.1 units/kg/hr', 'Potassium Chloride 20-30 mEq/L IV once K+ < 5.2 mEq/L', 'Switch to D5W 0.45% NaCl once blood glucose < 200 mg/dL'],
        monitoring_parameters=['Hourly point-of-care blood glucose', 'Basic metabolic panel and venous pH every 2 hours', 'Strict intake and output charting'],
        discharge_readiness_criteria=['Anion Gap closed (<= 12 mEq/L)', 'Serum bicarbonate >= 18 mEq/L and venous pH > 7.30', 'Blood glucose stable between 140-180 mg/dL', 'Successful transition to subcutaneous basal-bolus insulin with meal'],
        clinical_evidence_source="American Diabetes Association (ADA) Standards of Care in DKA",
    ),
};

class ClinicalPathwayEngine:
    @staticmethod
    def get_pathway(pathway_code: str) -> Optional[ClinicalPathway]:
        return CLINICAL_PATHWAYS_DATABASE.get(pathway_code.strip())

    @staticmethod
    def find_by_icd10(icd10_code: str) -> List[ClinicalPathway]:
        return [p for p in CLINICAL_PATHWAYS_DATABASE.values() if p.icd10_primary.startswith(icd10_code[:3])]

    @staticmethod
    def validate_admission_orders(pathway_code: str, ordered_tests: List[str], ordered_drugs: List[str]) -> Dict[str, Any]:
        pathway = CLINICAL_PATHWAYS_DATABASE.get(pathway_code)
        if not pathway:
            return {"status": "UNKNOWN_PATHWAY"}
        missing_tests = [t for t in pathway.stat_investigations if not any(t.lower() in o.lower() for o in ordered_tests)]
        return {
            "compliance_score_percent": max(0, 100 - len(missing_tests) * 15),
            "missing_stat_investigations": missing_tests,
            "is_fully_compliant": len(missing_tests) == 0
        }
