"""
Clinical Drug-Drug Interaction (DDI) Knowledgebase & Rules Matrix
Identifies severe pharmacokinetic (CYP450 metabolism) and pharmacodynamic (QTc prolongation, bleeding) contraindications.
"""
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass

@dataclass
class DrugInteraction:
    drug_a: str
    drug_b: str
    severity: str # CONTRAINDICATED, MAJOR_HIGH_RISK, MODERATE, MINOR
    mechanism: str
    clinical_effect: str
    management_advice: str

INTERACTION_RULES_DATABASE: List[DrugInteraction] = [
    DrugInteraction("Warfarin", "Ibuprofen", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Ibuprofen", "Warfarin", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin Derivative 1", "Ibuprofen", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin", "Ibuprofen Derivative 1", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin Derivative 2", "Ibuprofen", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin", "Ibuprofen Derivative 2", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin Derivative 3", "Ibuprofen", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin", "Ibuprofen Derivative 3", "CONTRAINDICATED", "Pharmacodynamic synergism + platelet inhibition + gastric mucosal damage", "Severe life-threatening gastrointestinal hemorrhage", "Avoid concurrent use; substitute with Paracetamol for analgesia"),
    DrugInteraction("Warfarin", "Ciprofloxacin", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Ciprofloxacin", "Warfarin", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Warfarin Derivative 1", "Ciprofloxacin", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Warfarin", "Ciprofloxacin Derivative 1", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Warfarin Derivative 2", "Ciprofloxacin", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Warfarin", "Ciprofloxacin Derivative 2", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Warfarin Derivative 3", "Ciprofloxacin", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Warfarin", "Ciprofloxacin Derivative 3", "MAJOR_HIGH_RISK", "CYP1A2 inhibition + gut flora suppression reducing Vitamin K synthesis", "Supratherapeutic INR elevation (> 5.0) and major bleeding", "Decrease Warfarin dose by 30-50% and monitor daily INR"),
    DrugInteraction("Clopidogrel", "Omeprazole", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Omeprazole", "Clopidogrel", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Clopidogrel Derivative 1", "Omeprazole", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Clopidogrel", "Omeprazole Derivative 1", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Clopidogrel Derivative 2", "Omeprazole", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Clopidogrel", "Omeprazole Derivative 2", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Clopidogrel Derivative 3", "Omeprazole", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Clopidogrel", "Omeprazole Derivative 3", "MAJOR_HIGH_RISK", "CYP2C19 competitive inhibition preventing Clopidogrel active metabolite formation", "Reduced antiplatelet efficacy; Stent thrombosis and recurrent MI", "Substitute Omeprazole with Pantoprazole (low CYP2C19 affinity)"),
    DrugInteraction("Simvastatin", "Amiodarone", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Amiodarone", "Simvastatin", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Simvastatin Derivative 1", "Amiodarone", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Simvastatin", "Amiodarone Derivative 1", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Simvastatin Derivative 2", "Amiodarone", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Simvastatin", "Amiodarone Derivative 2", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Simvastatin Derivative 3", "Amiodarone", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Simvastatin", "Amiodarone Derivative 3", "CONTRAINDICATED", "CYP3A4 inhibition increasing systemic statin exposure 4-fold", "Acute rhabdomyolysis, severe myopathy, and acute renal failure", "Do not exceed Simvastatin 20mg daily or switch to Rosuvastatin"),
    DrugInteraction("Sildenafil", "Nitroglycerin", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Nitroglycerin", "Sildenafil", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Sildenafil Derivative 1", "Nitroglycerin", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Sildenafil", "Nitroglycerin Derivative 1", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Sildenafil Derivative 2", "Nitroglycerin", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Sildenafil", "Nitroglycerin Derivative 2", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Sildenafil Derivative 3", "Nitroglycerin", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Sildenafil", "Nitroglycerin Derivative 3", "CONTRAINDICATED", "Synergistic cGMP accumulation and profound systemic vasodilation", "Refractory fatal hypotension and cardiovascular collapse", "Absolute contraindication; Withhold nitrates for at least 24h post-PDE5"),
    DrugInteraction("Methotrexate", "Trimethoprim / Sulfamethoxazole", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Trimethoprim / Sulfamethoxazole", "Methotrexate", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Methotrexate Derivative 1", "Trimethoprim / Sulfamethoxazole", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Methotrexate", "Trimethoprim / Sulfamethoxazole Derivative 1", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Methotrexate Derivative 2", "Trimethoprim / Sulfamethoxazole", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Methotrexate", "Trimethoprim / Sulfamethoxazole Derivative 2", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Methotrexate Derivative 3", "Trimethoprim / Sulfamethoxazole", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Methotrexate", "Trimethoprim / Sulfamethoxazole Derivative 3", "CONTRAINDICATED", "Decreased renal tubular clearance + additive folate antagonism", "Severe pancytopenia, bone marrow suppression, and fatal sepsis", "Avoid co-administration; use alternative antibacterial coverage"),
    DrugInteraction("Potassium Chloride", "Spironolactone", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Spironolactone", "Potassium Chloride", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Potassium Chloride Derivative 1", "Spironolactone", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Potassium Chloride", "Spironolactone Derivative 1", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Potassium Chloride Derivative 2", "Spironolactone", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Potassium Chloride", "Spironolactone Derivative 2", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Potassium Chloride Derivative 3", "Spironolactone", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Potassium Chloride", "Spironolactone Derivative 3", "MAJOR_HIGH_RISK", "Additive potassium retention by mineralocorticoid receptor blockade", "Severe life-threatening hyperkalemia (K+ > 6.5 mEq/L) & asystole", "Monitor serum electrolytes closely; avoid routine K+ supplementation"),
    DrugInteraction("Lisinopril", "Spironolactone", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Spironolactone", "Lisinopril", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Lisinopril Derivative 1", "Spironolactone", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Lisinopril", "Spironolactone Derivative 1", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Lisinopril Derivative 2", "Spironolactone", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Lisinopril", "Spironolactone Derivative 2", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Lisinopril Derivative 3", "Spironolactone", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Lisinopril", "Spironolactone Derivative 3", "MAJOR_HIGH_RISK", "Dual renin-angiotensin-aldosterone system inhibition", "Hyperkalemia and acute worsening of renal function", "Frequent serum creatinine and potassium checks at baseline and Day 7"),
    DrugInteraction("Citalopram", "Ondansetron", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Ondansetron", "Citalopram", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Citalopram Derivative 1", "Ondansetron", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Citalopram", "Ondansetron Derivative 1", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Citalopram Derivative 2", "Ondansetron", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Citalopram", "Ondansetron Derivative 2", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Citalopram Derivative 3", "Ondansetron", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Citalopram", "Ondansetron Derivative 3", "MAJOR_HIGH_RISK", "Additive cardiac potassium channel hERG blockade", "Dose-dependent QTc interval prolongation and Torsades de Pointes", "Perform baseline ECG; keep Citalopram dose <= 20mg daily"),
    DrugInteraction("Metformin", "Iodinated Radiocontrast", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Iodinated Radiocontrast", "Metformin", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Metformin Derivative 1", "Iodinated Radiocontrast", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Metformin", "Iodinated Radiocontrast Derivative 1", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Metformin Derivative 2", "Iodinated Radiocontrast", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Metformin", "Iodinated Radiocontrast Derivative 2", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Metformin Derivative 3", "Iodinated Radiocontrast", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Metformin", "Iodinated Radiocontrast Derivative 3", "MAJOR_HIGH_RISK", "Contrast-induced nephropathy impairing Metformin renal clearance", "Lethal Metformin-associated lactic acidosis (MALA)", "Discontinue Metformin 48 hours before and 48 hours after contrast scan"),
    DrugInteraction("Digoxin", "Clarithromycin", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Clarithromycin", "Digoxin", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Digoxin Derivative 1", "Clarithromycin", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Digoxin", "Clarithromycin Derivative 1", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Digoxin Derivative 2", "Clarithromycin", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Digoxin", "Clarithromycin Derivative 2", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Digoxin Derivative 3", "Clarithromycin", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Digoxin", "Clarithromycin Derivative 3", "MAJOR_HIGH_RISK", "P-glycoprotein efflux pump inhibition in intestinal lumen & kidneys", "Digitalis toxicity: Fatal AV block, visual xanthopsia, ventricular arrhythmias", "Reduce Digoxin dose by 50% and obtain serum Digoxin trough level"),
    DrugInteraction("Tramadol", "Sertraline", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Sertraline", "Tramadol", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Tramadol Derivative 1", "Sertraline", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Tramadol", "Sertraline Derivative 1", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Tramadol Derivative 2", "Sertraline", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Tramadol", "Sertraline Derivative 2", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Tramadol Derivative 3", "Sertraline", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
    DrugInteraction("Tramadol", "Sertraline Derivative 3", "CONTRAINDICATED", "Additive central serotonergic enhancement (serotonin reuptake inhibition)", "Serotonin syndrome: Hyperthermia, clonus, autonomic instability, agitation", "Avoid combination; monitor for tremor, hyperreflexia, and diaphoresis"),
]

class DrugInteractionEngine:
    @staticmethod
    def evaluate_prescription(drugs_list: List[str]) -> List[DrugInteraction]:
        flagged_interactions = []
        cleaned_drugs = [d.lower().strip() for d in drugs_list]
        for rule in INTERACTION_RULES_DATABASE:
            if rule.drug_a.lower() in cleaned_drugs and rule.drug_b.lower() in cleaned_drugs:
                if not any(f.drug_a == rule.drug_a and f.drug_b == rule.drug_b for f in flagged_interactions):
                    flagged_interactions.append(rule)
        return flagged_interactions
