"""
ApexCare Master Pharmacopeia & Therapeutic Formulary Classification
Defines detailed pharmacokinetic parameters, therapeutic ranges, bioavailabilities, and dosage forms.
"""
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

@dataclass
class PharmacopeiaItem:
    form_code: str
    generic_title: str
    chemical_class: str
    route_of_administration: str
    bioavailability_percent: float
    volume_of_distribution_l_kg: float
    plasma_protein_binding_pct: float
    metabolism_pathway: str
    elimination_route: str
    therapeutic_plasma_range: Optional[str]
    toxic_threshold: Optional[str]

PHARMACOPEIA_CATALOG: Dict[str, PharmacopeiaItem] = {
    "PHARM-DIG-01-001": PharmacopeiaItem(
        form_code="PHARM-DIG-01-001",
        generic_title="Digoxin Extended Formulation #1",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-002": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-002",
        generic_title="Phenytoin Sodium Extended Formulation #2",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-003": PharmacopeiaItem(
        form_code="PHARM-THEO-03-003",
        generic_title="Theophylline Extended Formulation #3",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-004": PharmacopeiaItem(
        form_code="PHARM-LITH-04-004",
        generic_title="Lithium Carbonate Extended Formulation #4",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-005": PharmacopeiaItem(
        form_code="PHARM-GENT-05-005",
        generic_title="Gentamicin Sulfate Extended Formulation #5",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-006": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-006",
        generic_title="Amikacin Sulfate Extended Formulation #6",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-007": PharmacopeiaItem(
        form_code="PHARM-VANC-07-007",
        generic_title="Vancomycin HCl Extended Formulation #7",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-008": PharmacopeiaItem(
        form_code="PHARM-TACR-08-008",
        generic_title="Tacrolimus Extended Formulation #8",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-009": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-009",
        generic_title="Cyclosporine Extended Formulation #9",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-010": PharmacopeiaItem(
        form_code="PHARM-CARB-10-010",
        generic_title="Carbamazepine Extended Formulation #10",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-011": PharmacopeiaItem(
        form_code="PHARM-DIG-01-011",
        generic_title="Digoxin Extended Formulation #11",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-012": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-012",
        generic_title="Phenytoin Sodium Extended Formulation #12",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-013": PharmacopeiaItem(
        form_code="PHARM-THEO-03-013",
        generic_title="Theophylline Extended Formulation #13",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-014": PharmacopeiaItem(
        form_code="PHARM-LITH-04-014",
        generic_title="Lithium Carbonate Extended Formulation #14",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-015": PharmacopeiaItem(
        form_code="PHARM-GENT-05-015",
        generic_title="Gentamicin Sulfate Extended Formulation #15",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-016": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-016",
        generic_title="Amikacin Sulfate Extended Formulation #16",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-017": PharmacopeiaItem(
        form_code="PHARM-VANC-07-017",
        generic_title="Vancomycin HCl Extended Formulation #17",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-018": PharmacopeiaItem(
        form_code="PHARM-TACR-08-018",
        generic_title="Tacrolimus Extended Formulation #18",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-019": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-019",
        generic_title="Cyclosporine Extended Formulation #19",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-020": PharmacopeiaItem(
        form_code="PHARM-CARB-10-020",
        generic_title="Carbamazepine Extended Formulation #20",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-021": PharmacopeiaItem(
        form_code="PHARM-DIG-01-021",
        generic_title="Digoxin Extended Formulation #21",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-022": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-022",
        generic_title="Phenytoin Sodium Extended Formulation #22",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-023": PharmacopeiaItem(
        form_code="PHARM-THEO-03-023",
        generic_title="Theophylline Extended Formulation #23",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-024": PharmacopeiaItem(
        form_code="PHARM-LITH-04-024",
        generic_title="Lithium Carbonate Extended Formulation #24",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-025": PharmacopeiaItem(
        form_code="PHARM-GENT-05-025",
        generic_title="Gentamicin Sulfate Extended Formulation #25",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-026": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-026",
        generic_title="Amikacin Sulfate Extended Formulation #26",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-027": PharmacopeiaItem(
        form_code="PHARM-VANC-07-027",
        generic_title="Vancomycin HCl Extended Formulation #27",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-028": PharmacopeiaItem(
        form_code="PHARM-TACR-08-028",
        generic_title="Tacrolimus Extended Formulation #28",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-029": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-029",
        generic_title="Cyclosporine Extended Formulation #29",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-030": PharmacopeiaItem(
        form_code="PHARM-CARB-10-030",
        generic_title="Carbamazepine Extended Formulation #30",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-031": PharmacopeiaItem(
        form_code="PHARM-DIG-01-031",
        generic_title="Digoxin Extended Formulation #31",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-032": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-032",
        generic_title="Phenytoin Sodium Extended Formulation #32",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-033": PharmacopeiaItem(
        form_code="PHARM-THEO-03-033",
        generic_title="Theophylline Extended Formulation #33",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-034": PharmacopeiaItem(
        form_code="PHARM-LITH-04-034",
        generic_title="Lithium Carbonate Extended Formulation #34",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-035": PharmacopeiaItem(
        form_code="PHARM-GENT-05-035",
        generic_title="Gentamicin Sulfate Extended Formulation #35",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-036": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-036",
        generic_title="Amikacin Sulfate Extended Formulation #36",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-037": PharmacopeiaItem(
        form_code="PHARM-VANC-07-037",
        generic_title="Vancomycin HCl Extended Formulation #37",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-038": PharmacopeiaItem(
        form_code="PHARM-TACR-08-038",
        generic_title="Tacrolimus Extended Formulation #38",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-039": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-039",
        generic_title="Cyclosporine Extended Formulation #39",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-040": PharmacopeiaItem(
        form_code="PHARM-CARB-10-040",
        generic_title="Carbamazepine Extended Formulation #40",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-041": PharmacopeiaItem(
        form_code="PHARM-DIG-01-041",
        generic_title="Digoxin Extended Formulation #41",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-042": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-042",
        generic_title="Phenytoin Sodium Extended Formulation #42",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-043": PharmacopeiaItem(
        form_code="PHARM-THEO-03-043",
        generic_title="Theophylline Extended Formulation #43",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-044": PharmacopeiaItem(
        form_code="PHARM-LITH-04-044",
        generic_title="Lithium Carbonate Extended Formulation #44",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-045": PharmacopeiaItem(
        form_code="PHARM-GENT-05-045",
        generic_title="Gentamicin Sulfate Extended Formulation #45",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-046": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-046",
        generic_title="Amikacin Sulfate Extended Formulation #46",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-047": PharmacopeiaItem(
        form_code="PHARM-VANC-07-047",
        generic_title="Vancomycin HCl Extended Formulation #47",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-048": PharmacopeiaItem(
        form_code="PHARM-TACR-08-048",
        generic_title="Tacrolimus Extended Formulation #48",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-049": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-049",
        generic_title="Cyclosporine Extended Formulation #49",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-050": PharmacopeiaItem(
        form_code="PHARM-CARB-10-050",
        generic_title="Carbamazepine Extended Formulation #50",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-051": PharmacopeiaItem(
        form_code="PHARM-DIG-01-051",
        generic_title="Digoxin Extended Formulation #51",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-052": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-052",
        generic_title="Phenytoin Sodium Extended Formulation #52",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-053": PharmacopeiaItem(
        form_code="PHARM-THEO-03-053",
        generic_title="Theophylline Extended Formulation #53",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-054": PharmacopeiaItem(
        form_code="PHARM-LITH-04-054",
        generic_title="Lithium Carbonate Extended Formulation #54",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-055": PharmacopeiaItem(
        form_code="PHARM-GENT-05-055",
        generic_title="Gentamicin Sulfate Extended Formulation #55",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-056": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-056",
        generic_title="Amikacin Sulfate Extended Formulation #56",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-057": PharmacopeiaItem(
        form_code="PHARM-VANC-07-057",
        generic_title="Vancomycin HCl Extended Formulation #57",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-058": PharmacopeiaItem(
        form_code="PHARM-TACR-08-058",
        generic_title="Tacrolimus Extended Formulation #58",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-059": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-059",
        generic_title="Cyclosporine Extended Formulation #59",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-060": PharmacopeiaItem(
        form_code="PHARM-CARB-10-060",
        generic_title="Carbamazepine Extended Formulation #60",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-061": PharmacopeiaItem(
        form_code="PHARM-DIG-01-061",
        generic_title="Digoxin Extended Formulation #61",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-062": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-062",
        generic_title="Phenytoin Sodium Extended Formulation #62",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-063": PharmacopeiaItem(
        form_code="PHARM-THEO-03-063",
        generic_title="Theophylline Extended Formulation #63",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-064": PharmacopeiaItem(
        form_code="PHARM-LITH-04-064",
        generic_title="Lithium Carbonate Extended Formulation #64",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-065": PharmacopeiaItem(
        form_code="PHARM-GENT-05-065",
        generic_title="Gentamicin Sulfate Extended Formulation #65",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-066": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-066",
        generic_title="Amikacin Sulfate Extended Formulation #66",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-067": PharmacopeiaItem(
        form_code="PHARM-VANC-07-067",
        generic_title="Vancomycin HCl Extended Formulation #67",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-068": PharmacopeiaItem(
        form_code="PHARM-TACR-08-068",
        generic_title="Tacrolimus Extended Formulation #68",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-069": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-069",
        generic_title="Cyclosporine Extended Formulation #69",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
    "PHARM-CARB-10-070": PharmacopeiaItem(
        form_code="PHARM-CARB-10-070",
        generic_title="Carbamazepine Extended Formulation #70",
        chemical_class="Iminostilbene Anticonvulsant",
        route_of_administration="Oral Extended-Release",
        bioavailability_percent=85.0,
        volume_of_distribution_l_kg=1.4,
        plasma_protein_binding_pct=76.0,
        metabolism_pathway="Hepatic CYP3A4 (Auto-induction of metabolism)",
        elimination_route="Renal excretion (72%)",
        therapeutic_plasma_range="4.0 - 12.0 mcg/mL",
        toxic_threshold="> 12.0 mcg/mL",
    ),
    "PHARM-DIG-01-071": PharmacopeiaItem(
        form_code="PHARM-DIG-01-071",
        generic_title="Digoxin Extended Formulation #71",
        chemical_class="Cardiac Glycoside",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=75.0,
        volume_of_distribution_l_kg=7.3,
        plasma_protein_binding_pct=25.0,
        metabolism_pathway="Hepatic minimal (16%)",
        elimination_route="Renal glomerular filtration (80%)",
        therapeutic_plasma_range="0.8 - 2.0 ng/mL",
        toxic_threshold="> 2.0 ng/mL",
    ),
    "PHARM-PHEN-02-072": PharmacopeiaItem(
        form_code="PHARM-PHEN-02-072",
        generic_title="Phenytoin Sodium Extended Formulation #72",
        chemical_class="Hydantoin Anticonvulsant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=90.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP2C9 / CYP2C19 (Michaelis-Menten kinetics)",
        elimination_route="Renal inactive metabolites",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-THEO-03-073": PharmacopeiaItem(
        form_code="PHARM-THEO-03-073",
        generic_title="Theophylline Extended Formulation #73",
        chemical_class="Methylxanthine Bronchodilator",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=96.0,
        volume_of_distribution_l_kg=0.5,
        plasma_protein_binding_pct=40.0,
        metabolism_pathway="Hepatic CYP1A2 (90%)",
        elimination_route="Renal excretion",
        therapeutic_plasma_range="10.0 - 20.0 mcg/mL",
        toxic_threshold="> 20.0 mcg/mL",
    ),
    "PHARM-LITH-04-074": PharmacopeiaItem(
        form_code="PHARM-LITH-04-074",
        generic_title="Lithium Carbonate Extended Formulation #74",
        chemical_class="Mood Stabilizer",
        route_of_administration="Oral Capsule / Tablet",
        bioavailability_percent=95.0,
        volume_of_distribution_l_kg=0.8,
        plasma_protein_binding_pct=0.0,
        metabolism_pathway="None (not metabolized by liver)",
        elimination_route="Renal proximal tubular clearance (95%)",
        therapeutic_plasma_range="0.6 - 1.2 mEq/L",
        toxic_threshold="> 1.5 mEq/L",
    ),
    "PHARM-GENT-05-075": PharmacopeiaItem(
        form_code="PHARM-GENT-05-075",
        generic_title="Gentamicin Sulfate Extended Formulation #75",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous / Intramuscular",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.25,
        plasma_protein_binding_pct=10.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal glomerular filtration (100%)",
        therapeutic_plasma_range="Peak: 5-10 mcg/mL, Trough: < 2 mcg/mL",
        toxic_threshold="Trough > 2.0 mcg/mL",
    ),
    "PHARM-AMIK-06-076": PharmacopeiaItem(
        form_code="PHARM-AMIK-06-076",
        generic_title="Amikacin Sulfate Extended Formulation #76",
        chemical_class="Aminoglycoside Antibiotic",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.26,
        plasma_protein_binding_pct=11.0,
        metabolism_pathway="None (not metabolized)",
        elimination_route="Renal excretion (98%)",
        therapeutic_plasma_range="Peak: 20-30 mcg/mL, Trough: < 5 mcg/mL",
        toxic_threshold="Trough > 10.0 mcg/mL",
    ),
    "PHARM-VANC-07-077": PharmacopeiaItem(
        form_code="PHARM-VANC-07-077",
        generic_title="Vancomycin HCl Extended Formulation #77",
        chemical_class="Glycopeptide Antibacterial",
        route_of_administration="Intravenous Infusion",
        bioavailability_percent=100.0,
        volume_of_distribution_l_kg=0.7,
        plasma_protein_binding_pct=50.0,
        metabolism_pathway="Minimal hepatic metabolism",
        elimination_route="Renal excretion (85%)",
        therapeutic_plasma_range="Trough: 15.0 - 20.0 mcg/mL",
        toxic_threshold="Trough > 25.0 mcg/mL",
    ),
    "PHARM-TACR-08-078": PharmacopeiaItem(
        form_code="PHARM-TACR-08-078",
        generic_title="Tacrolimus Extended Formulation #78",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral / Intravenous",
        bioavailability_percent=25.0,
        volume_of_distribution_l_kg=1.0,
        plasma_protein_binding_pct=99.0,
        metabolism_pathway="Extensive hepatic CYP3A4 metabolism",
        elimination_route="Biliary and fecal elimination",
        therapeutic_plasma_range="5.0 - 15.0 ng/mL",
        toxic_threshold="> 20.0 ng/mL",
    ),
    "PHARM-CYCL-09-079": PharmacopeiaItem(
        form_code="PHARM-CYCL-09-079",
        generic_title="Cyclosporine Extended Formulation #79",
        chemical_class="Calcineurin Inhibitor Immunosuppressant",
        route_of_administration="Oral Microemulsion",
        bioavailability_percent=30.0,
        volume_of_distribution_l_kg=4.5,
        plasma_protein_binding_pct=90.0,
        metabolism_pathway="Hepatic CYP3A4 (P-glycoprotein substrate)",
        elimination_route="Biliary excretion (94%)",
        therapeutic_plasma_range="100 - 300 ng/mL",
        toxic_threshold="> 400 ng/mL",
    ),
};

class TherapeuticDrugMonitoringService:
    @staticmethod
    def get_pharmacopeia_item(form_code: str) -> Optional[PharmacopeiaItem]:
        return PHARMACOPEIA_CATALOG.get(form_code.strip())

    @staticmethod
    def estimate_steady_state_concentration(daily_dose_mg: float, clearance_l_hr: float, bioavailability: float = 1.0) -> float:
        if clearance_l_hr <= 0:
            return 0.0
        dosing_rate_mg_hr = daily_dose_mg / 24.0
        css_mg_l = (bioavailability * dosing_rate_mg_hr) / clearance_l_hr
        return round(css_mg_l, 3)
